# Zero Trust Workload Identity Manager configuration
apiVersion: operator.openshift.io/v1alpha1
kind: ZeroTrustWorkloadIdentityManager
metadata:
  name: cluster
  labels:
    app.kubernetes.io/name: zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: zero-trust-workload-identity-manager
spec:
  trustDomain: "apps.rosa.rosa-v99n5.8ie9.p3.openshiftapps.com"
  clusterName: "rosa-v99n5"
  bundleConfigMap: "spire-bundle"
